-- 1. Tabelle für die Prorektor:innen
CREATE TABLE IF NOT EXISTS PROREKTORAT (
    ProrektorID SERIAL PRIMARY KEY,
    Vorname VARCHAR(50) NOT NULL,
    Nachname VARCHAR(50) NOT NULL,
    E_Mail VARCHAR(100) NOT NULL UNIQUE
);

-- 2. Tabelle für die Lehrpersonen
CREATE TABLE IF NOT EXISTS LEHRPERSON (
    LehrpersonID SERIAL PRIMARY KEY,
    Vorname VARCHAR(50) NOT NULL,
    Nachname VARCHAR(50) NOT NULL,
    E_Mail VARCHAR(100) NOT NULL UNIQUE
);

-- 3. Tabelle für die Lernenden
CREATE TABLE IF NOT EXISTS LERNENDER (
    LernenderID SERIAL PRIMARY KEY,
    Vorname VARCHAR(50) NOT NULL,
    Nachname VARCHAR(50) NOT NULL,
    Klasse VARCHAR(10)
);

-- 4. Tabelle für die Module
CREATE TABLE IF NOT EXISTS MODUL (
    ModulID SERIAL PRIMARY KEY,
    Modulname VARCHAR(100) NOT NULL UNIQUE,
    Semester INT
);

-- ENUM-Typ für Status
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'status_enum') THEN
        CREATE TYPE status_enum AS ENUM (
            'EINGEREICHT',
            'GEPRUEFT_JA',
            'GEPRUEFT_NEIN',
            'ANS_SEKRETARIAT_UEBERMITTELT'
        );
    END IF;
END$$;

-- Zentrale Antrags-Tabelle
CREATE TABLE IF NOT EXISTS NOTENANPASSUNG_ANTRAG (
    AntragID SERIAL PRIMARY KEY,

    LehrpersonID INT NOT NULL REFERENCES LEHRPERSON(LehrpersonID),
    ProrektorID INT NOT NULL REFERENCES PROREKTORAT(ProrektorID), 
    LernenderID INT NOT NULL REFERENCES LERNENDER(LernenderID),
    ModulID INT NOT NULL REFERENCES MODUL(ModulID),

    AlteNote NUMERIC(3,2), 
    NeueNote NUMERIC(3,2) NOT NULL,

    Antragsdatum TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Bemerkungen TEXT,

    Status status_enum NOT NULL DEFAULT 'EINGEREICHT',
    Pruefungsdatum TIMESTAMP NULL,
    Ablehnungsgrund TEXT
);

INSERT INTO LEHRPERSON (Vorname, Nachname, E_Mail) VALUES
('Julia','Abächerli','julia.abaecherli@gibz.ch'),
('Tobias','Acklin','tobias.acklin@gibz.ch'),
('Sandra','Affentranger','sandra.affentranger@gibz.ch'),
('Sira','Alder','sira.alder@gibz.ch'),
('Raphael','Alt','raphael.alt@gibz.ch'),
('Simon','Althaus','simon.althaus@gibz.ch'),
('Hans','Amberg','hans.amberg@gibz.ch'),
('Bernadette','Ammann','bernadette.ammann@gibz.ch'),
('Niklaus','Anklin','niklaus.anklin@gibz.ch'),
('Sonja','Appert','sonja.appert@gibz.ch'),
('Jessica','Aregger','jessica.aregger@gibz.ch'),
('Myriam','Arnelas','myriam.arnelas@gibz.ch'),
('Markus','Attinger','markus.attinger@gibz.ch'),
('Philippe','Babey','philippe.babey@gibz.ch'),
('Mathias','Bachmann','mathias.bachmann@gibz.ch'),
('Pascal','Bammert','pascal.bammert@gibz.ch'),
('Michael','Barry','michael.barry@gibz.ch'),
('Ueli','Baumann','ueli.baumann@gibz.ch'),
('Ulrich','Baur','ulrich.baur@gibz.ch'),
('Elia','Becci','elia.becci@gibz.ch'),
('Valentin','Beduhn','valentin.beduhn@gibz.ch'),
('Reto','Benz','reto.benz@gibz.ch'),
('Markus','Betschart','markus.betschart@gibz.ch'),
('Marc','Bettschen','marc.bettschen@gibz.ch'),
('Chiara','Bieler','chiara.bieler@gibz.ch'),
('Carina','Bieri','carina.bieri@gibz.ch'),
('Silvan','Bieri','silvan.bieri@gibz.ch'),
('Stefan','Blättler','stefan.blaettler@gibz.ch'),
('Margrit','Bolliger','margrit.bolliger@gibz.ch'),
('Eva Linda','Borsai','linda.borsai@gibz.ch'),
('David','Bradley','david.bradley@gibz.ch'),
('Miriam','Braun','miriam.braun@gibz.ch'),
('Stephan','Brehm','stephan.brehm@gibz.ch'),
('Sibylle','Bucher','sibylle.bucher@gibz.ch'),
('Carmen','Buder','carmen.buder@gibz.ch'),
('Timon','Burkard','timon.burkard@gibz.ch'),
('Nicola','Büttiker','nbuettiker@gibz.ch'),
('Adriano','Carminitana','adriano.carminitana@gibz.ch'),
('Patrick','Carulli','patrick.carulli@gibz.ch'),
('Nathalie','Casillo','nathalie.casillo@gibz.ch'),
('Lino','Cerletti','lcerletti2@gibz.ch'),
('Raul','Costa','raul.costa@gibz.ch'),
('Giuseppe','Cucuzza','giuseppe.cucuzza@gibz.ch'),
('Pascal','Derungs','pascal.derungs@gibz.ch'),
('Christian','Deuber','christian.deuber@gibz.ch'),
('Corinne','Di Tizio-Schneider','cditizio@gibz.ch'),
('Géraldine','Dietrich','geraldine.dietrich@gibz.ch'),
('Bettina','Dober','bettina.dober@gibz.ch'),
('Christoph','Eggenspieler','christoph.eggenspieler@gibz.ch'),
('Susanne','Eglauf','susanne.eglauf@gibz.ch'),
('Daniel','Eichmüller','daniel.eichmueller@gibz.ch'),
('Karla','Emich-Kohler','karla_emich@bluewin.ch'),
('Antonia','Erni','antonia.erni@gibz.ch'),
('Fabienne','Erzinger','fabienne.erzinger@gibz.ch'),
('Matthias','Essig','matthias.essig@gibz.ch'),
('Janine','Ezer','janine.ezer@gibz.ch'),
('Reto','Fessler','reto.fessler@gibz.ch'),
('Tobias','Feusi','tobias.feusi@gibz.ch'),
('Remo','Flury','remo.flury@gibz.ch'),
('Roland','Frei','roland.frei@gibz.ch'),
('Christian','Freimann','christian.freimann@gibz.ch'),
('Estefania Cristina','Frei-Otero','estefania.frei@gibz.ch'),
('Antoinette','Freivogel','antoinette.freivogel@gibz.ch'),
('Nora','Frey','nora.frey@gibz.ch'),
('Paul M.','Furrer','paul.furrer@gibz.ch'),
('Tanja','Furrer','tanja.furrer@gibz.ch'),
('Elio','Gallo','elio.gallo@gibz.ch'),
('Beate','Gau','beate.gau@gibz.ch'),
('Kevin','Gehrig','kevin.gehrig@gibz.ch'),
('Peter','Gisler','peter.gisler@gibz.ch'),
('Dominik','Gmür','dominik.gmuer@gibz.ch'),
('Christoph','Goechnahts','christoph.goechnahts@gibz.ch'),
('Andri','Good','andri.good@gibz.ch'),
('Florian','Graf','florian.graf@gibz.ch'),
('Reto','Grepper','reto.grepper@gibz.ch'),
('Martin','Greutmann','martin.greutmann@gibz.ch'),
('Markus','Gut','markus.gut@gibz.ch'),
('Jean-Luc','Haas','jeanluc.haas@gibz.ch'),
('Alexandra','Haas-Bauer','alexandra.haas@gibz.ch'),
('Roman','Hatz','roman.hatz@gibz.ch'),
('Anke','Hauenschild','anke.hauenschild@gibz.ch'),
('Simon','Haueter','simon.haueter@gibz.ch'),
('Jasmin','Hauri','jasmin.hauri@gibz.ch'),
('Regula','Hauser','regula.hauser@gibz.ch'),
('Thomas','Hausheer','thomas.hausheer@gibz.ch'),
('Christian','Hegglin','christian.hegglin@gibz.ch'),
('Claudia','Hegglin','claudia.hegglin@gibz.ch'),
('Daniela','Hegglin','daniela.hegglin@gibz.ch'),
('Urs','Hegglin','urs.hegglin@gibz.ch'),
('Peter','Hegi','peter.hegi@gibz.ch'),
('Martin','Hegner','mартin.hegner@gibz.ch'),
('Christoph','Heimburger','christoph.heimburger@gibz.ch'),
('Daniel','Henggeler','daniel.henggeler@gibz.ch'),
('Patricia','Heraty','patricia.heraty@gibz.ch'),
('Philipp','Herzog','philipp.herzog@gibz.ch'),
('Markus','Hostettler','markus.hostettler@gibz.ch'),
('Daniel','Huber','daniel.huber@hfzug.ch'),
('Claudio','Hübscher','claudio.huebscher@gibz.ch'),
('Franz','Hürlimann','franz.huerlimann@gibz.ch'),
('Tanja','Imgrüth','tanja.imgrueth@gibz.ch'),
('Erna','Inderbitzin','erna.inderbitzin@gibz.ch'),
('Ramona','Isler','ramona.isler@gibz.ch'),
('Annette','Iten','annette.iten@gibz.ch'),
('Tabea','Jung','tabea.jung@gibz.ch'),
('Saira','Kaufmann','saira.kaufmann@gibz.ch'),
('Corinne','Kelly','corinne.kelly@gibz.ch'),
('Heinz','Klein','heinz.klein@gibz.ch'),
('Ernst','Kleiner','ernst.kleiner@gibz.ch'),
('Pascale','Koller','pascale.koller@gibz.ch'),
('Taha Sabri','Koltukluoglu','taha.koltukluoglu@gibz.ch'),
('Pascale','Köppel-Van Puyenbroeck','pascale.koeppel@gibz.ch'),
('Jürg','Körner','juerg.koerner@gibz.ch'),
('Ulrich','Kössl','ulrich.koessl@gibz.ch'),
('Michael','Krieger','michael.krieger@gibz.ch'),
('Carla','Kronig','carla.kronig@gibz.ch'),
('Stephan','Krummenacher','stephan.krummenacher@gibz.ch'),
('Cornelia','Kuhles','cornelia.kuhles@gibz.ch'),
('Beat','Kündig','beat.kuendig@gibz.ch'),
('Benjamin','Landolt','benjamin.landolt@gibz.ch'),
('Florian','Landtwing','florian.landtwing@gibz.ch'),
('Julia','Leibacher','julia.leibacher@gibz.ch'),
('Christian','Lindauer','christian.lindauer@gibz.ch'),
('Lilian','Lischer','lilian.lischer@gibz.ch'),
('Elena','Lorenzo Albor','elena.lorenzo@gibz.ch'),
('Sabrina','Lötscher','sabrina.loetscher@gibz.ch'),
('Caroline','Lüscher','caroline.luescher@gibz.ch'),
('Monika','Makart-Hofer','monika.makart@gibz.ch'),
('Thomas','Marbacher','thomas.marbacher@gibz.ch'),
('Manuela','Marty','manuela.marty@gibz.ch'),
('Arthur','Mathis','arthur.mathis@gibz.ch'),
('Marco','Mehr','marco.mehr@gibz.ch'),
('Michael Richard','Mettler','michael.mettler@gibz.ch'),
('Laura','Moell','laura.moell@gibz.ch'),
('Claudio','Moos','claudio.moos@gibz.ch'),
('Aaron','Moser','aaron.moser@gibz.ch'),
('Roger','Muggli','roger.muggli@gibz.ch'),
('Loris','Müller','loris.mueller@gibz.ch'),
('Roger','Müller','roger.mueller@gibz.ch'),
('Dummy','Mustermann','bschilliger@gibz.ch'),
('Jürg','Neidhart','juerg.neidhart@gibz.ch'),
('Simon','Neidhart','simon.neidhart@gibz.ch'),
('Markus','Nussbaumer','markus.nussbaumer2@gibz.ch'),
('Thomas','Oberlin','thomas.oberlin@gibz.ch'),
('Maria','Odermatt','maria.odermatt@gibz.ch'),
('Bernhard','Parodi','bernhard.parodi@gibz.ch'),
('Chiara','Parodi','chiara.parodi@gibz.ch'),
('Giancarlo','Pascarella','giancarlo.pascarella@gibz.ch'),
('Raabe','Pauli','raabe.pauli@gibz.ch'),
('Regula','Pauli-Roggli','regula.pauli@gibz.ch'),
('Markus','Perchtaler','markus.perchtaler@gibz.ch'),
('Fabio','Petranca','fabio.petranca@gibz.ch'),
('Tobias','Pulfer','tobias.pulfer@gibz.ch'),
('Matthias','Püntener','matthias.puentener@gibz.ch'),
('Rajmonda','Quni','rajmonda.quni@gibz.ch'),
('Silvan','Renggli','silvan.renggli@gibz.ch'),
('Stefan','Rickli','stefan.rickli@gibz.ch'),
('Roger','Rogenmoser','roger.rogenmoser@gibz.ch'),
('Manuel Christoph','Rohrer','manuel.rohrer@gibz.ch'),
('Yasmin','Rohrer','yasmin.rohrer@gibz.ch'),
('Lorenz','Roos','lorenz.roos@gibz.ch'),
('Sabrina','Rüegg','sabrina.rueegg@gibz.ch'),
('Szabolcs','Sajo','szabolcs.sajo@gibz.ch'),
('Marcus','Schawalder','marcus.schawalder@gibz.ch'),
('Daniel','Scherrer','daniel.scherrer@gibz.ch'),
('Simon','Schibig','simon.schibig@gibz.ch'),
('Robert','Schlittler','robert.schlittler@gibz.ch'),
('Silvio','Schlumpf','silvio.schlumpf@gibz.ch'),
('René','Schmid','rene.schmid@gibz.ch'),
('Tobias','Schmid','tobias.schmid@gibz.ch'),
('Willi','Schmidt','willi.schmidt@gibz.ch'),
('Patrick','Schnieper','patrick.schnieper@gibz.ch'),
('Edith','Schöb','edith.schoeb@gibz.ch'),
('Astrid','Schönenberger','astrid.schoenenberger@gibz.ch'),
('Peter','Schork','peter.schork@gibz.ch'),
('Edith','Schurtenberger','edith.schurtenberger@gibz.ch'),
('Noëlla Patricia','Schüttel','noella.schuettel@gibz.ch'),
('Markus','Schwindl','markus.schwindl@gibz.ch'),
('Manuela','Speck','manuela.speck@gibz.ch'),
('Niklaus','Stadelmann','niklaus.stadelmann@gibz.ch'),
('Philipp','Stalder','philipp.stalder@gibz.ch'),
('David','Stamm','david.stamm@gibz.ch'),
('Corina','Steffen','corina.steffen@gibz.ch'),
('Michele Salvatore','Stranieri','michele.stranieri@gibz.ch'),
('Ivo','Strebel','ivo.strebel@gibz.ch'),
('GIBZ','Stundenplanung','stundenplanung@gibz.ch'),
('Robert','Theiler','robert.theiler@gibz.ch'),
('Andreja','Torriani','andreja.torriani@gibz.ch'),
('Markus','Trinkler','markus.trinkler@gibz.ch'),
('David','Trost','david.trost@gibz.ch'),
('Jack','Trythall','jack.trythall@gibz.ch'),
('Ermira','Tuzi','ermira.tuzi@gibz.ch'),
('Denis','Vejnovic','denis.vejnovic@gibz.ch'),
('Goran','Vejnovic','goran.vejnovic@gibz.ch'),
('Miriam','Vollmer','miriam.vollmer@gibz.ch'),
('Beat','von Holzen','beat.vonholzen@gibz.ch'),
('Anita','Vonchristen','anita.vonchristen@gibz.ch'),
('Irène','Waldispühl','irene.waldispuehl@gibz.ch'),
('Julian','Wasem','julian.wasem@gibz.ch'),
('Gabriel','Weber','gabriel.weber@gibz.ch'),
('Raphael','Weiss','raphael.weiss@gibz.ch'),
('Sonja','Werne','sonja.werne@gibz.ch'),
('Manuela','Wey','manuela.wey@gibz.ch'),
('Roger','Wiedemeier','roger.wiedemeier@gibz.ch'),
('Christoph','Wildhaber','christoph.wildhaber@gibz.ch'),
('Dominik','Windlin','dominik.windlin@gibz.ch'),
('Andrea','Winkler','andrea.winkler@gibz.ch'),
('Lukas Emanuel','Winter','lukas.winter@gibz.ch'),
('Reto','Wirz','reto.wirz@gibz.ch'),
('Peter','Wlodarczak','peter.wlodarczak@gibz.ch'),
('Karl','Wüest-Schöpfer','karl.wueest@gibz.ch'),
('Marcel','Würsch','marcel.wuersch@gibz.ch'),
('Özkan','Yapici','oezkan.yapici@gibz.ch'),
('Armin','Zaugg','armin.zaugg@gibz.ch'),
('Beat','Zgraggen','beat.zgraggen@gibz.ch'),
('Katja','Zgraggen','katja.zgraggen@gibz.ch'),
('Marco','Ziegler','marco.ziegler@gibz.ch'),
('Marco','Zimmermann','marco.zimmermann@gibz.ch'),
('Pascal','Zumbühl','pascal.zumbuehl@gibz.ch'),
('Sandra','Zurbuchen','sandra.zurbuchen@gibz.ch'),
('Guido','Trachsler','guido.trachsler@zg.ch'),
('Mark','Zurfluh','mark.zurfluh@gibz.ch');

